apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sso-forward-auth.yaml
  - security-headers.yaml
  - profiles.yaml
  - default-public.yaml
  - local-cert-file-provider.yaml
  - dashboard.yaml
