apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "${RABBITMQ_INTERNAL_CREDENTIALS_STATIC_SECRET_NAME}"
  namespace: "${RABBITMQ_NAMESPACE}"
spec:
  type: kv-v2
  mount: "${RABBITMQ_INTERNAL_CREDENTIALS_VAULT_MOUNT}"
  path: "${RABBITMQ_INTERNAL_CREDENTIALS_VAULT_PATH}"
  destination:
    name: "${RABBITMQ_INTERNAL_CREDENTIALS_SECRET_NAME}"
    create: true
  refreshAfter: "${RABBITMQ_INTERNAL_CREDENTIALS_REFRESH_AFTER}"
  vaultAuthRef: "${RABBITMQ_VAULT_AUTH_REF}"
