apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: "${GATEWAY_API_CLASS_NAME}"
  labels:
    app.kubernetes.io/part-of: platform-edge
spec:
  controllerName: "${GATEWAY_API_CONTROLLER_NAME}"
  description: "${GATEWAY_API_CLASS_DESCRIPTION}"
