apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: "${LONGHORN_HELM_REPOSITORY_NAME}"
  namespace: "${LONGHORN_NAMESPACE}"
spec:
  interval: "${LONGHORN_HELM_REPOSITORY_INTERVAL}"
  url: "${LONGHORN_HELM_REPOSITORY_URL}"
